version: "3"

services:

  trainer:
    build: .
    # restart: unless-stopped
    environment:
      - SOCKET=3990
      - PORT=3999
      - TIMEOUT=30
    volumes:
      - ./data/app:/app
      - ./data/unit:/unit
    command: python /app/launch.py
    ports:
      - 3990:3990
      - 3999:3999
    networks:
      - network

networks:
  network:
    name: prod_network
    external: true
