version: "3"

services:

  php:
    build: .
    restart: unless-stopped
    env_file:
      - ../../.env
    volumes:
      - ../../data/.ssh:/.ssh
      - ../../data/php/conf.d:/usr/local/etc/php/conf.d
      - ../../data/php/supervisor.d:/etc/supervisor.d
      - ../../project/:/var/www
    working_dir: /var/www/
    ports:
      - 9000:9000
    networks:
      - network

networks:
  network:
    name: prod_network
    external: true
