version: "3"

services:

  api:
    build: .
    restart: unless-stopped
    env_file:
      - ../../.env
    volumes:
      - ../../project/api:/var/www
    working_dir: /var/www
    command: >
      bash -c "yarn
      && yarn prisma generate
      && yarn start"
    ports:
      - 5000:5000
    networks:
      - network

networks:
  network:
    name: prod_network
    external: true
