version: "3"

services:

  adminer:
    extends:
      file: ./services/adminer/docker-compose.yml
      service: adminer
#  git:
#    extends:
#      file: ./services/git/docker-compose.yml
#      service: git
#  mongo:
#    extends:
#      file: ./services/mongo/docker-compose.yml
#      service: mongo
  mysql:
    extends:
      file: ./services/mysql/docker-compose.yml
      service: mysql
  nginx:
    extends:
      file: ./services/nginx/docker-compose.yml
      service: nginx
#  nodejs:
#    extends:
#      file: ./services/nodejs/docker-compose.yml
#      service: nodejs
  pgadmin:
    extends:
      file: ./services/pgadmin/docker-compose.yml
      service: pgadmin
  php:
    extends:
      file: ./services/php/docker-compose.yml
      service: php
  phpmyadmin:
    extends:
      file: ./services/phpmyadmin/docker-compose.yml
      service: phpmyadmin
#  poste:
#    extends:
#      file: ./services/poste/docker-compose.yml
#      service: poste
  postgres:
    extends:
      file: ./services/postgres/docker-compose.yml
      service: postgres
#  python:
#    extends:
#      file: ./services/python/docker-compose.yml
#      service: python
#  redis:
#    extends:
#      file: ./services/redis/docker-compose.yml
#      service: redis
#  redis-commander:
#    extends:
#      file: ./services/redis-commander/docker-compose.yml
#      service: redis-commander

networks:
  network:
    name: prod_network
    driver: bridge
