version: "3"

services:

  api:
    extends:
      file: ./service/api/docker-compose.yml
      service: api

  auth:
    extends:
      file: ./service/auth/docker-compose.yml
      service: auth

  static:
    extends:
      file: ./service/static/docker-compose.yml
      service: static

  nginx:
    extends:
      file: ./service/nginx/docker-compose.yml
      service: nginx

#  python:
#    extends:
#      file: ./service/python/docker-compose.yml
#      service: python

  php:
    extends:
      file: ./service/php/docker-compose.yml
      service: php

  adminer:
    extends:
      file: ./service/db/docker-compose.yml
      service: adminer

  mysql:
    extends:
      file: ./service/db/docker-compose.yml
      service: mysql

  phpmyadmin:
    extends:
      file: ./service/db/docker-compose.yml
      service: phpmyadmin

  postgres:
    extends:
      file: ./service/db/docker-compose.yml
      service: postgres

  pgadmin:
    extends:
      file: ./service/db/docker-compose.yml
      service: pgadmin

#  redis:
#    extends:
#      file: ./service/db/docker-compose.yml
#      service: redis
#
#  redis-commander:
#    extends:
#      file: ./service/db/docker-compose.yml
#      service: redis-commander
#
#  mongo:
#    extends:
#      file: ./service/db/docker-compose.yml
#      service: mongo
#
#  git:
#    extends:
#      file: ./service/git/docker-compose.yml
#      service: git
#
#  mail:
#    extends:
#      file: ./service/mail/docker-compose.yml
#      service: mail

networks:
  network:
    name: prod_network
    driver: bridge
