version: "3"

services:

  api:
    extends:
      file: ./server/api/docker-compose.yml
      service: api

  auth:
    extends:
      file: ./server/auth/docker-compose.yml
      service: auth

  static:
    extends:
      file: ./server/static/docker-compose.yml
      service: static

  nginx:
    extends:
      file: ./server/nginx/docker-compose.yml
      service: nginx

  python:
    extends:
      file: ./server/python/docker-compose.yml
      service: python

  php:
    extends:
      file: ./server/php/docker-compose.yml
      service: php

  adminer:
    extends:
      file: ./server/db/docker-compose.yml
      service: adminer

  mysql:
    extends:
      file: ./server/db/docker-compose.yml
      service: mysql

  phpmyadmin:
    extends:
      file: ./server/db/docker-compose.yml
      service: phpmyadmin

  postgres:
    extends:
      file: ./server/db/docker-compose.yml
      service: postgres

  pgadmin:
    extends:
      file: ./server/db/docker-compose.yml
      service: pgadmin

#  redis:
#    extends:
#      file: ./server/db/docker-compose.yml
#      service: redis
#
#  redis-commander:
#    extends:
#      file: ./server/db/docker-compose.yml
#      service: redis-commander
#
#  mongo:
#    extends:
#      file: ./server/db/docker-compose.yml
#      service: mongo
#
#  git:
#    extends:
#      file: ./server/git/docker-compose.yml
#      service: git
#
#  mail:
#    extends:
#      file: ./server/mail/docker-compose.yml
#      service: mail

networks:
  network:
    name: prod_network
    driver: bridge

#networks:
#  network:
#    driver: bridge
