version: "3"

services:

  comfyui:
    extends:
      file: ./services/comfyui/docker-compose.yml
      service: comfyui

  jupyter:
    extends:
      file: ./services/jupyter/docker-compose.yml
      service: jupyter

  llm:
    extends:
      file: ./services/llm/docker-compose.yml
      service: llm

  lmstudio:
    extends:
      file: ./services/lmstudio/docker-compose.yml
      service: lmstudio

  localai:
    extends:
      file: ./services/localai/docker-compose.yml
      service: localai

  ollama:
    extends:
      file: ./services/ollama/docker-compose.yml
      service: ollama

  openwebui:
    extends:
      file: ./services/openwebui/docker-compose.yml
      service: openwebui

  python:
    extends:
      file: ./services/python/docker-compose.yml
      service: python

  qwenvl:
    extends:
      file: ./services/qwenvl/docker-compose.yml
      service: qwenvl

  sd-webui-forge:
    extends:
      file: ./services/sd-webui-forge/docker-compose.yml
      service: sd-webui-forge

  vllm:
    extends:
      file: ./services/vllm/docker-compose.yml
      service: vllm

networks:
  network:
    name: ai_network
    driver: bridge
