version: "3"

services:

  cpp:
    build: .
    environment:
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ./data:/app/src
    working_dir: /app/src
    stdin_open: true
    ports:
      - 7000:7000
    networks:
      - network

networks:
  network:
    name: prod_network
    external: true
