version: "3"

services:

  cpp:
    build: .
    environment:
      - PORT=${CPP_PORT}
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ./data:/app/src
    working_dir: /app/src
    stdin_open: true
    ports:
      - ${CPP_PORT}:${CPP_PORT}
    networks:
      - network

networks:
  network:
    name: prod_network
    external: true
