version: "3"

services:

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ../../.env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${POSTGRES_USER}@${POSTGRES_HOST}.sql
      - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    networks:
      - network

networks:
  network:
    name: prod_network
    external: true
