version: "3"

services:

  mongo:
    image: mongo:4.2
    env_file:
      - ../../.env
    environment:
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ../../data/mongo/configdb:/data/configdb
      - ../../data/mongo/db:/data/db
      - ../../data/mongo/dump:/dump
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - network

networks:
  network:
    name: prod_network
    external: true
