version: "3"

services:

  locust:
    build: .
    environment:
      - TZ=${WORKSPACE_TIMEZONE}
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    env_file:
      - ../../.env
    volumes:
      - ./data:/var/www
    working_dir: /var/www
    command: locust
    # command: locust -V
    # command: locust -f locustfile.py --host=http://nestapi.ru:5000 --csv report
    ports:
      - ${LOCUST_PORT}:8089
    networks:
      - network

networks:
  network:
    name: prod_network
    external: true
