version: "3"

services:

  comfyui:
    image: yanwk/comfyui-boot:cu124-slim
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      # - NVIDIA_VISIBLE_DEVICES=0
    restart: unless-stopped
    env_file:
      - ../../.env
    volumes:
      - ./data:/root
      # - ./data:/root/ComfyUI
    ports:
      - 8288:8188
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
              count: all 
              # count: 1
              # options:
              #   com.nvidia.cuda.visible_devices: "0"
    networks:
      - network

networks:
  network:
    name: prod_network
    external: true
