version: "3"

services:

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
      - ../../project/:/var/www
    ports:
      - 80:80
      - 443:443
    networks:
      - network

networks:
  network:
    name: prod_network
    external: true

#networks:
#  network:
#    name: prod_network
#    driver: bridge
