version: "3"

services:

  redis-commander:
    image: rediscommander/redis-commander:latest
    hostname: ${REDIS_COMMANDER_HOST}
    restart: always
    env_file:
      - ../../.env
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - ${REDIS_COMMANDER_PORT}:8081
    networks:
      - network

networks:
  network:
    name: prod_network
    external: true
