version: "3"

services:

  python:
    build: .
    environment:
      - TZ=${WORKSPACE_TIMEZONE}
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    env_file:
      - ../../.env
    volumes:
      - ../.ssh:/.ssh
      - ../../projects/:/var/www
    working_dir: /var/www
    tty: true
    restart: no
    stdin_open: true
    # command: gunicorn -w 4 script:app
    ports:
      - 8000:8000
    networks:
      - network

networks:
  network:
    name: prod_network
    external: true
