version: "3"

services:

  python:
    build: .
    restart: unless-stopped
    environment:
      - TZ=${WORKSPACE_TIMEZONE}
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ../../projects:/var/www
    working_dir: /var/www/
    ports:
      - 8000:8000
    networks:
      - network

networks:
  network:
    name: prod_network
    external: true
