version: "3"

services:

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    env_file:
      - ../../.env
    volumes:
      - ./data/nginx.conf:/etc/nginx/nginx.conf
      - ./data/conf.d:/etc/nginx/conf.d
      - ./data/ssl:/etc/nginx/ssl
      - ./data/log:/var/log/nginx
      - ../.certs:/etc/.certs
      - ../../projects:/var/www
    ports:
      - ${NGINX_PORT}:80
      - ${NGINX_SSL_PORT}:443
    networks:
      - network

networks:
  network:
    name: prod_network
    external: true
