version: "3"

services:

  postgres:
    image: postgres:alpine
    hostname: ${POSTGRES_HOST}
    env_file:
      - ../../.env
    environment:
      - TZ=${WORKSPACE_TIMEZONE}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data/lib:/var/lib/postgresql/data
      - ./data/dump:/dump
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - network

networks:
  network:
    name: prod_network
    external: true
