version: "3"

services:

  nextcloud:
    image: nextcloud:stable-fpm
    restart: always
    env_file:
      - ../../.env
    # environment:
    #   - ADMINER_DEFAULT_SERVER=${MYSQL_HOST}
    # volumes:
    #   - ./data:/
    # ports:
    #   - ${NEXTCLOUD_PORT}:8080
    networks:
      - network

networks:
  network:
    name: prod_network
    external: true
