version: "3"

services:

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    command: server --console-address ":9001" /data/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./data:/data
    ports:
      - 9990:9000
      - 9991:9001
    networks:
      - network

  minio-client:
    image: minio/mc
    restart: unless-stopped
    # npm install --save minio nestjs-minio-client
    # https://habr.com/ru/companies/ozontech/articles/586024/
    # command: >
    #   bash -c "mc alias set myminio/ http://localhost:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} && mc ls myminio/mybucket"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./data:/data
    ports:
      - 9999:80
    networks:
      - network

networks:
  network:
    name: prod_network
    external: true
