FROM nvidia/cuda:12.9.0-cudnn-devel-ubuntu20.04
# FROM conda/miniconda3

WORKDIR /app

RUN apt update

# установка зависимостей
# RUN apt update \
#     && apt install -y --no-install-recommends \
#         bash \
#         build-essential \
#         cmake \
#         curl \
#         gcc gcc-multilib g++ \
#         git \
#         libglib2.0-0 \
#         software-properties-common \
#         wget
# 
# RUN rm -rf /var/lib/apt/lists/*
