version: "3"

services:

  redis:
    image: redis:latest
    env_file:
      - ../../.env
    environment:
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ./data/conf:/usr/local/etc/redis/redis.conf
      - ./data/lib:/var/lib/redis
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - network

networks:
  network:
    name: prod_network
    external: true
