version: "3"

services:

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    env_file:
      - ../../.env
    environment:
      - TZ=${WORKSPACE_TIMEZONE}
      - PMA_ARBITRARY=1
      - MYSQL_HOST=${MYSQL_HOST}
    volumes:
      - ./data:/usr/local/etc/php/conf.d
    ports:
      - ${PHPMYADMIN_PORT}:80
    networks:
      - network

networks:
  network:
    name: prod_network
    external: true
