version: "3.7"

services:
  pdf:
    build: .
    restart: unless-stopped
    init: true
    env_file:
      - ./.env
    volumes:
      - ./:/var/www
    working_dir: /var/www/
    command: >
      bash -c "npm i && npm run start"
    ports:
      - "${PORT:-3000}:3000"
    networks:
      - network

networks:
  network:
    name: prod_network
    external: true
