version: "3"

services:

  adminer:
    image: adminer
    restart: always
    env_file:
      - ../../.env
    environment:
      - ADMINER_DEFAULT_SERVER=${MYSQL_HOST}
    volumes:
      - ../../data/db/adminer:/etc/php/7.4/cli/conf.d
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - network

  mysql:
    image: mysql:8.0.29
    hostname: ${MYSQL_HOST}
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    env_file:
      - ../../.env
    environment:
      - TZ=${WORKSPACE_TIMEZONE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ../../data/db/mysql/conf.d:/etc/mysql/conf.d
      - ../../data/db/mysql/data:/var/lib/mysql
      - ../../data/db/mysql/logs:/var/log/mysql
      - ../../data/db/mysql/dump:/dump
    command: --default-authentication-plugin=mysql_native_password --skip_name_resolve
    depends_on:
      - phpmyadmin
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - network

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    env_file:
      - ../../.env
    environment:
      - TZ=${WORKSPACE_TIMEZONE}
      - PMA_ARBITRARY=1
      - MYSQL_HOST=${MYSQL_HOST}
    volumes:
      - ../../data/db/phpmyadmin:/usr/local/etc/php/conf.d
    ports:
      - ${PHPMYADMIN_PORT}:80
    networks:
      - network

  postgres:
    image: postgres:alpine
    hostname: ${POSTGRES_HOST}
    env_file:
      - ../../.env
    environment:
      - TZ=${WORKSPACE_TIMEZONE}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ../../data/db/postgres/data:/var/lib/postgresql/data
      - ../../data/db/postgres/dump:/dump
    depends_on:
      - pgadmin
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - network

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ../../.env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${POSTGRES_USER}@${POSTGRES_HOST}.sql
      - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    networks:
      - network

  #redis:
  #  image: redis:latest
  #  env_file:
  #    - ../../.env
  #  environment:
  #    - TZ=${WORKSPACE_TIMEZONE}
  #  volumes:
  #    - ../../data/db/redis/conf:/usr/local/etc/redis/redis.conf
  #    - ../../data/db/redis/data:/var/lib/redis
  #  depends_on:
  #    - redis-commander
  #  ports:
  #    - ${REDIS_PORT}:6379
  #  networks:
  #    - network

  #redis-commander:
  #  image: rediscommander/redis-commander:latest
  #  hostname: ${REDIS_COMMANDER_HOST}
  #  restart: always
  #  env_file:
  #    - ../../.env
  #  environment:
  #    - REDIS_HOSTS=local:redis:6379
  #  ports:
  #    - ${REDIS_COMMANDER_PORT}:8081
  #  networks:
  #    - network

  #mongo:
  #  image: mongo:4.2
  #  env_file:
  #    - ../../.env
  #  environment:
  #    - TZ=${WORKSPACE_TIMEZONE}
  #  volumes:
  #    - ../../data/db/mongo/configdb:/data/configdb
  #    - ../../data/db/mongo/db:/data/db
  #    - ../../data/db/mongo/dump:/dump
  #  ports:
  #    - ${MONGO_PORT}:27017
  #  networks:
  #    - network

networks:
  network:
    name: prod_network
    external: true
