version: "3"

services:

  nodejs:
    build: .
    restart: unless-stopped
    env_file:
      - ../../.env
    volumes:
      - ../../projects:/var/www
    working_dir: /var/www
    # command: >
    #   bash -c "yarn && yarn start"
    ports:
      - 3000:3000
      - 8080:8080
    networks:
      - network

networks:
  network:
    name: prod_network
    external: true
