version: "3"

services:

  nodejs:
    build: .
    restart: unless-stopped
    env_file:
      - ../../.env
    volumes:
      - ../../projects:/var/www
    working_dir: /var/www
    tty: true
    ports:
      - 3000:3000
      - 5000:5000
      - 8080:8080
      - 8081:8081
    networks:
      - network

networks:
  network:
    name: prod_network
    external: true
